services:
  todo-app-backend:
    build: ./backend
    depends_on:
      todo-app-db:
        condition: service_healthy
    ports: 
      - 8000:8000
    restart: always
    container_name: todo-app-backend
    networks:
      - todo-app-network
  todo-app-frontend:
    build: ./frontend
    depends_on:
      - todo-app-backend
    ports: 
      - 3000:3000
    restart: always
    container_name: todo-app-frontend
    networks:
      - todo-app-network
  todo-app-db:
    image: mysql:latest
    restart: always
    env_file:
      - ./db/.env
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    volumes:
      - ./db/dump:/docker-entrypoint-initdb.d
      - ./db/dbdata:/var/lib/mysql
    container_name: todo-app-db
    networks:
      - todo-app-network

networks:
  todo-app-network:
    driver: bridge

